language: rust
os:
  - linux
services:
  - memcached
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly
script:
  - ([ $TRAVIS_RUST_VERSION == nightly ] || cargo build)
  - ([ $TRAVIS_RUST_VERSION != nightly ] || cargo build --features nightly)
  - ([ $TRAVIS_RUST_VERSION == nightly ] || cargo test)
  - ([ $TRAVIS_RUST_VERSION != nightly ] || cargo test --features nightly)
  - ([ $TRAVIS_RUST_VERSION != nightly ] || cargo bench --features nightly)
