language: rust
os:
  - linux
services:
  - memcached
rust:
  - stable
  - beta
  - nightly
script:
  - ([ $TRAVIS_RUST_VERSION == nightly ] || cargo test)
  - ([ $TRAVIS_RUST_VERSION != nightly ] || cargo test --features with-serde)
  - ([ $TRAVIS_RUST_VERSION != nightly ] || cargo test --features nightly)
  - ([ $TRAVIS_RUST_VERSION != nightly ] || cargo bench --features nightly)
