[package]
name = "tokio-memcache"
version = "0.0.1"
authors = ["svartalf <self@svartalf.info>"]

[dependencies]
futures = "*"
tokio-core = "*"
tokio-service = "*"
tokio-proto = "*"
byteorder = "*"
enum_primitive = "*"
