[package]
name = "tokio-memcache"
description = "Tokio memcache client. WIP"
version = "0.0.2"
repository = "https://github.com/svartalf/tokio-memcache"
authors = ["svartalf <self@svartalf.info>"]
keywords = ["tokio", "futures", "memcache", "memcached"]
categories = ["asynchronous", "caching"]
travis-ci = { repository = "https://github.com/svartalf/tokio-memcache", branch = "master" }
license = "Apache-2.0"

[features]
default = []
nightly = ["clippy"]
# TODO: Since Cargo features are addictive, `with-serde` may break everything eventually
# if one copy of library will be compiled with it and another without it in one application.
with-serde = ["serde", "rmp-serde"]

[dependencies]
futures = "~0.1"
tokio-core = "~0.1"
tokio-service = "~0.1"
tokio-proto = "~0.1"
byteorder = "~1.0"
enum_primitive = "~0.1"
log = "~0.3"

serde = { version = "*", optional = true }
rmp-serde = { version = "*", optional = true }

clippy = { version = "0.0.116", optional = true }
